name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Platane/snk@v3
        with:
          github_user_name: shahrozebaig
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        run: |
          cd dist
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git init
          git add github-contribution-grid-snake.svg
          git commit -m "Generate snake animation"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}